### ISSUE TITLE
run without color

### ISSUE THREAD

**Issue by zachcheung** [timescale/timescaledb-tune#123]
```go
	flag.BoolVar(&f.UseColor, "color", true, "Use color in output (works best on dark terminals)")
```

Firstly, sorry for ignoring the issue template.

Shouldn't it be `nocolor` with default `false` here? How can it run without color when the default way is `color` and the flag is to enable color?

**Comment by RafiaSabih** [comment]
@zachcheung Thanks for taking time out for reporting this, but can you please elaborate on what is the project you are facing this issue with and other details.

**Comment by zachcheung** [comment]
<img width="662" alt="timescaledb-tune" src="https://github.com/timescale/timescaledb-tune/assets/964285/bd24ff55-5a40-4bb4-baab-e6e082fc66b4">

@RafiaSabih As you can see, `timescaledb-tune` uses color in output by default, and there's a `-color` option there but since the default is `true` so I don't think it's possible to disable color.

```
# timescaledb-tune -h
Usage of timescaledb-tune:
  -color
        Use color in output (works best on dark terminals) (default true)
```

**Comment by jnidzwetzki** [comment]
Hello @zachcheung,

Thanks for reaching out. To run `timescaledb-tune` without color, you can use the flag `--color=false`. For example: `timescaledb-tune --color=false`.

Does this work in your environment or are colors still displayed afterwards?

**Comment by zachcheung** [comment]
@jnidzwetzki Wow, I didn't know it's possible to set value to bool flag in go. It works, and thank you for letting me know.
