### ISSUE TITLE
max_connections

### ISSUE THREAD

**Issue by kanazir** [timescale/timescaledb-tune#47]
The app changes max_connections to 50. I think it should not touch this setting...

**Comment by RobAtticus** [comment]
This is settable by the user via flag `--max-conns`, also you are always free to reject recommended settings at the prompt. That said, we will be increasing this in the next version (probably to 100). Or do you have another recommendation for it?

**Comment by kanazir** [comment]
Maybe it should leave the setting as it is? I am not sure why the app changes max_connections at all?

**Comment by RobAtticus** [comment]
We create background workers who take some of the connections so we want to make sure that instances have a sufficient amount of background workers and for connections. Other tools like pgtune may also have given users a poor value and we want to make sure it is giving a good recommendation.

But as said, the tool allows you to accept/skip settings so you don't have to take its recommendation.

**Comment by kanazir** [comment]
I understand now. Thank you :)
