### ISSUE TITLE
No way to set max_connections > 100?

### ISSUE THREAD

**Issue by rickbatka** [timescale/timescaledb-tune#54]
Hi,

I'm trying to create a timescale docker image that will override a few config defaults, run timescaledb-tune, and start up all in one action without needing to run timescale-tune, stop the server, make my additional config changes, and restart.

I took a page out of your docker file and decided to override the settings I care about in postgresql.conf.sample (remember, I want this tuning to happen **and be applied** on first startup of the container).

Here's the entirety of my docker file:
```
FROM timescale/timescaledb:1.3.2-pg11
RUN sed -r -i "s/[#]*\s*max_connections\s*=.*/max_connections = 1024/" /usr/local/share/postgresql/postgresql.conf.sample
RUN sed -r -i "s/[#]*\s*timezone\s*=.*/timezone = 'UTC'/" /usr/local/share/postgresql/postgresql.conf.sample
RUN sed -r -i "s/[#]*\s*synchronous_commit\s*=.*/synchronous_commit = off/" /usr/local/share/postgresql/postgresql.conf.sample
```

Two of my settings make it through (timezone and synchronous_commit), but max_connections is always reset to 100.

(I've verified my changes are indeed being applied properly in /usr/local/share/postgresql/postgresql.conf.sample, so it's timescaledb-tune that's nuking it)

Is there any way to selectively tune the configuration or provide manual overrides? I'm a bit stuck as to how I can deploy this to different hardware with a combination of automatic tuning and my custom settings.

Any guidance is much appreciated!

**Comment by dianasaur323** [comment]
@RobAtticus mind taking a look?

**Comment by RobAtticus** [comment]
Hey @rickbatka, you probably want to actually include a docker entrypoint script to do the change instead, since timescaledb-tune runs on container startup. Anything in the Dockerfile will get overwritten in that case.

We should probably expose a catch all `TIMESCALEDB_TUNE_FLAGS` var that can be set since it is possible to tell `timescaledb-tune` which number it should use for `max_connections`. Or perhaps the logic should change that if `max_connections` is `>=` to our recommendation, to just use that.

That said, `1024` seems a bit high and could negatively affect your query performance by reducing the amount of work mem for each.

**Comment by rickbatka** [comment]
> you probably want to actually include a docker entrypoint script to do the change instead, since timescaledb-tune runs on container startup

I see what you mean. Unfortunately the timescale docker behavior is to run timescaledb-tune and then immediately start the database. Since that startup script overwrites that value, I would have to  write my own docker entrypoint, that did everything the current one does except also make this one change *after* timescale-tune, before starting the database. And now I've effectively forked away from the timescale docker image.

To your other points, I think it would be helpful if there were a way to affect the behavior of timescale-tune such that we could not tune certain settings that we want to set manually.

**Comment by dianasaur323** [comment]
cc @bboule perhaps something for you to keep an eye on

**Comment by sign0** [comment]
I did almost the same thing as you... : [sign0/postgis-timescale-h3/initdb-extensions.sh#L92](https://github.com/sign0/postgis-timescale-h3/blob/master/initdb-extensions.sh#L92)

And, I modify my "work_mem" to 104kB as recommended here for 1000 connections : [pgtune](https://pgtune.leopard.in.ua)

**Comment by tomw1808** [comment]
I second that, it would be amazing to tell timescale via environment variables what to do (or not to do).

**Comment by jflambert** [comment]
@rickbatka  you can now use `TS_TUNE_MAX_CONNS`
