### ISSUE TITLE
[DEBIAN 10] -bash: timescaledb-tune: command not found

### ISSUE THREAD

**Issue by augustomurri** [timescale/timescaledb-tune#65]
`root@SQLECOFIL1:~# apt-get install timescaledb-postgresql-11
Reading package lists... Done
Building dependency tree
Reading state information... Done
timescaledb-postgresql-11 is already the newest version (1.6.1~debian10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@SQLECOFIL1:~# timescaledb-tune
**-bash: timescaledb-tune: command not found**
root@SQLECOFIL1:~#
`

cannot find timescaledb-tune.... Installed Go .. then GIT
`root@SQLECOFIL1:~# go get github.com/timescale/timescaledb-tune/cmd/timescaledb-tune
root@SQLECOFIL1:~# timescaledb-tune
**-bash: timescaledb-tune: command not found**
`

nothing

Debian GNU/Linux 10 \n \l

**Comment by ohaibbq** [comment]
Hi @augustomurri, have you added Go to your `$PATH`?

```bash
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
```

**Comment by augustomurri** [comment]
> Hi @augustomurri, have you added Go to your `$PATH`?
> 
> ```shell
> export GOPATH="$HOME/go"
> export PATH="$PATH:$GOPATH/bin"
> ```

mmm no. It works now. thanks
