### ISSUE TITLE
timescaledb-tune invocation fails

### ISSUE THREAD

**Issue by sujeet01** [timescale/timescaledb-tune#66]
After doing go get, I tried calling timescaledb-tune which returned `EXIT: unknown major PG version: PostgreSQL 12.0`

**Comment by mfreed** [comment]
TimescaleDB does not currently support PG12.  We will be releasing support for PG12 in our next release, v1.7.

**Comment by mfreed** [comment]
Actually, I might have closed this too early...but could this be related to installing via helm?

https://github.com/timescale/timescaledb-tune/issues/61

**Comment by sujeet01** [comment]
No, I was trying to install timescaledb with postgres 12. So when you said it's not supported then I tried it with postgres 11 and it worked fine.
