### ISSUE TITLE
Tuner recommends a much lower shared_buffers value than the recommended 25% of memory

### ISSUE THREAD

**Issue by fergus3000** [timescale/timescaledb-tune#68]
I was reading the recent guidance from @mfreed on [setting up timescale for insert performance](https://github.com/timescale/docs.timescale.com-content/issues/294) Note point 5 "we typically recommend 25% of available RAM" - this seems to be in line with the general best practice for postgresql.

I was surprised that timescaledb-tune had set shared_buffers to only 512mb on my 14Gb machine, I changed the setting manually to 3.5gb but was concerned the tuner hadn't run correctly first time, so I re-ran it. The tuner recognized my machine had 14Gb ram, but again recommended setting shared_buffers to 512mb.

Now I'm not sure whether I should believe the tuner's recommendations - how is it arriving at such a low value?

**Comment by RobAtticus** [comment]
Hey @fergus3000 ! I think the issue may be that you're running this on Windows, is that correct? Windows behaves differently than Linux/OSX when it comes to shared_buffers, so 512MB is actually the recommended max.

Some more information on shared_buffers is here:
https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server

If you're OS is _not_ Windows, then it is a bug.

**Comment by fergus3000** [comment]
Thanks for the clarification. I wasn’t aware of the difference between windows and Linux for this setting, so it’s my mistake. 

Now I wonder whether I still have to chose a chunk size within the shared buffers size. 512mb is much too small for the amount of data we want to get per chunk. We’re actually only using a windows server to quickly test whether timescale is going to work for us.
