### ISSUE TITLE
Support for Postgres 13?

### ISSUE THREAD

**Issue by yazeed** [timescale/timescaledb-tune#74]
Does this work with Postgres 13, or is a PR needed?

Getting this error on a Cloud SQL instance on Google Cloud.

`
exit: unknown major PG version: PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1)
`

**Comment by mfreed** [comment]
TimescaleDB has not yet released support for PG13 (we expect in TimescaleDB 2.1).    But I'm slightly confused given that I don't think Google Cloud SQL has any support for TimescaleDB?  Or are you just looking to use this to tune your vanilla PG instance?

**Comment by rahulmutt** [comment]
Running into the same issue when trying to tune https://github.com/timescale/timescaledb/releases/tag/2.1.0 which should support Postgres 13. Is there a PR planned for this or should I give it a try?

**Comment by svenklemm** [comment]
https://github.com/timescale/timescaledb-tune/pull/77

**Comment by rahulmutt** [comment]
Verified that the updates work, thanks!
